export const EXAMPLE_ACTIONS = {
    EXAMPLE: "EXAMPLE"
};

export const RESUME_ACTIONS = {
    SET_DATA: "RESUME_ACTIONS_SET_DATA"
};

export const CONSULTANT_LIST_ACTIONS = {
    SET_DATA: "CONSULTANT_LIST_ACTIONS_SET_DATA"
};
